name: 'Build HydePHP Site'
description: 'Build and deploy the HydePHP project'
branding:
  icon: 'box'
  color: 'purple'

inputs:
  debug:
    description: 'Enable debug mode'
    required: false
    default: "false"

  deploy-to:
    # Pages option requires GitHub the "Build and deployment" source to be set to "GitHub Actions"
    # You must also ensure that GITHUB_TOKEN has permission "id-token: write".
    description: 'Specify what to do with the compiled site. Options are: [artifact, pages]'
    required: true
    default: "artifact"

  upload-artifact:
    description: 'Upload the compiled site as an artifact'
    required: false
    default: "false"

  framework-version:
    description: 'The framework version of HydePHP to install (only applicable when using archive install strategy)'
    required: false
    default: "latest"

  directory:
    description: 'The project root directory'
    required: false
    default: "."

  env-site-name:
    description: 'Set the `SITE_NAME` environment variable'
    required: false
  env-site-url:
    description: 'Set the `SITE_URL` environment variable'
    required: false
  env-torchlight-token:
    description: 'Set the `TORCHLIGHT_TOKEN` environment variable'
    required: false

outputs:
  install-strategy:
    description: 'The install strategy used'
    value: ${{ steps.determine-install-strategy.outputs.install-strategy }}

runs:
  using: "composite"
  steps:
    - name: Add action path to GitHub PATH
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Validate input
      id: validate-input
      run: bash validate-input.sh ${{ inputs.deploy-to }}
      shell: bash

    - name: Determine install strategy
      id: determine-install-strategy
      run: bash determine-install-strategy.sh
      shell: bash

    - name: Print debug information
      if: inputs.debug == 'true'
      run: |
        echo "Debug mode: ${{ inputs.debug }}"
        echo "Deployment option: ${{ inputs.deploy-to }}"
        echo "Install strategy: ${{ steps.determine-install-strategy.outputs.install-strategy }}"
        echo action_path: ${{ github.action_path }}
      shell: bash

    - name: Validate composer.json and composer.lock
      if: steps.determine-install-strategy.outputs.install-strategy == 'composer'
      run: composer validate --strict
      shell: bash

    - name: Cache Composer packages
      id: composer-cache
      if: steps.determine-install-strategy.outputs.install-strategy == 'composer'
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Download latest release
      if: steps.determine-install-strategy.outputs.install-strategy == 'archive'
      run: bash download-latest-release.sh ${{ inputs.framework-version }}
      shell: bash

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-autoloader && composer dump-autoload --quiet
      shell: bash

    - name: Set up environment variables
      run: bash setup-environment-variables.sh
      shell: bash

    # Inject environment variables
    - if: inputs.env-site-name != ''
      run: echo "SITE_NAME=${{ inputs.env-site-name }}" >> .env
      shell: bash
    - if: inputs.env-site-url != ''
      run: echo "SITE_URL=${{ inputs.env-site-url }}" >> .env
      shell: bash
    - if: inputs.env-torchlight-token != ''
      run: echo "TORCHLIGHT_TOKEN=${{ inputs.env-torchlight-token }}" >> .env
      shell: bash

    - name: Build the site
      run: php hyde build --no-interaction --ansi
      shell: bash

    - name: Upload artifact
      if: inputs.deploy-to == 'artifact' || inputs.upload-artifact == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: _site # TODO: Get this from the config file in case it's customized

    - name: Setup Pages
      if: inputs.deploy-to == 'pages'
      uses: actions/configure-pages@v3

    - name: Upload artifact
      if: inputs.deploy-to == 'pages'
      uses: actions/upload-pages-artifact@v1
      with:
        path: _site # TODO: Get this from the config file in case it's customized

    - name: Deploy to GitHub Pages
      id: pages-deployment
      if: inputs.deploy-to == 'pages'
      uses: actions/deploy-pages@v1

    # Now that the site is built, there are a few options for deployment.
    # We could push directly to the gh-pages branch, commit files to /docs,
    # or even use the GitHub Pages action to deploy the compiled site.
    # We could also upload the site as an artifact for later use.
